package org.opendatamesh.platform.pp.registry.rest.v2.resources.dataproduct.events.received;

import io.swagger.v3.oas.annotations.media.Schema;
import org.opendatamesh.platform.pp.registry.rest.v2.resources.dataproduct.DataProductRes;

@Schema(name = "ReceivedEventDataProductInitializationRequestedRes", description = "Strongly-typed representation of a received DATA_PRODUCT_INITIALIZATION_REQUESTED event")
public class ReceivedEventDataProductInitializationRequestedRes {
    @Schema(description = "Unique identifier of the event (autogenerated sequence ID)", example = "42")
    private Long sequenceId;

    @Schema(description = "Type of the resource that generated the event", example = "DATA_PRODUCT")
    private String resourceType;

    @Schema(description = "Identifier of the resource that generated the event", example = "d5b5b9ac-6a73-4c73-b9ce-4bfc10a1dba0")
    private String resourceIdentifier;

    @Schema(description = "Type of event emitted", example = "DATA_PRODUCT_INITIALIZATION_REQUESTED")
    private String type;

    @Schema(description = "Version of the event type definition", example = "1.0.0")
    private String version;

    @Schema(description = "Strongly-typed content of the event")
    private EventContent content;

    public ReceivedEventDataProductInitializationRequestedRes() {
    }

    public Long getSequenceId() {
        return sequenceId;
    }

    public void setSequenceId(Long sequenceId) {
        this.sequenceId = sequenceId;
    }

    public String getResourceType() {
        return resourceType;
    }

    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    public String getResourceIdentifier() {
        return resourceIdentifier;
    }

    public void setResourceIdentifier(String resourceIdentifier) {
        this.resourceIdentifier = resourceIdentifier;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public EventContent getContent() {
        return content;
    }

    public void setContent(EventContent content) {
        this.content = content;
    }

    @Schema(name = "EventContent", description = "Strongly-typed event content for DATA_PRODUCT_INITIALIZATION_REQUESTED")
    public static class EventContent {
        @Schema(description = "The data product that was requested for initialization")
        private DataProductRes dataProduct;

        public EventContent() {
        }

        public DataProductRes getDataProduct() {
            return dataProduct;
        }

        public void setDataProduct(DataProductRes dataProduct) {
            this.dataProduct = dataProduct;
        }
    }
}

