package org.opendatamesh.platform.pp.registry.rest.v2.resources.dataproduct.events.received;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(name = "ReceivedEventDataProductRejectedRes", description = "Strongly-typed representation of a received DATA_PRODUCT_INITIALIZATION_REJECTED event")
public class ReceivedEventDataProductRejectedRes {
    @Schema(description = "Unique identifier of the event (autogenerated sequence ID)", example = "42")
    private Long sequenceId;

    @Schema(description = "Type of the resource that generated the event", example = "DATA_PRODUCT")
    private String resourceType;

    @Schema(description = "Identifier of the resource that generated the event", example = "d5b5b9ac-6a73-4c73-b9ce-4bfc10a1dba0")
    private String resourceIdentifier;

    @Schema(description = "Type of event emitted", example = "DATA_PRODUCT_INITIALIZATION_REJECTED")
    private String type;

    @Schema(description = "Version of the event type definition", example = "1.0.0")
    private String eventTypeVersion;

    @Schema(description = "Strongly-typed content of the event")
    private EventContent eventContent;

    public ReceivedEventDataProductRejectedRes() {
    }

    public Long getSequenceId() {
        return sequenceId;
    }

    public void setSequenceId(Long sequenceId) {
        this.sequenceId = sequenceId;
    }

    public String getResourceType() {
        return resourceType;
    }

    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    public String getResourceIdentifier() {
        return resourceIdentifier;
    }

    public void setResourceIdentifier(String resourceIdentifier) {
        this.resourceIdentifier = resourceIdentifier;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getEventTypeVersion() {
        return eventTypeVersion;
    }

    public void setEventTypeVersion(String eventTypeVersion) {
        this.eventTypeVersion = eventTypeVersion;
    }

    public EventContent getEventContent() {
        return eventContent;
    }

    public void setEventContent(EventContent eventContent) {
        this.eventContent = eventContent;
    }

    @Schema(name = "EventContent", description = "Strongly-typed event content for DATA_PRODUCT_INITIALIZATION_REJECTED")
    public static class EventContent {
        @Schema(description = "The data product that was rejected")
        private DataProduct dataProduct;

        public EventContent() {
        }

        public DataProduct getDataProduct() {
            return dataProduct;
        }

        public void setDataProduct(DataProduct dataProduct) {
            this.dataProduct = dataProduct;
        }
    }

    @Schema(name = "DataProduct", description = "Lightweight data product information")
    public static class DataProduct {
        @Schema(description = "Unique identifier of the data product", example = "d5b5b9ac-6a73-4c73-b9ce-4bfc10a1dba0")
        private String uuid;

        @Schema(description = "Fully qualified name of the data product", example = "domain:name:version")
        private String fqn;

        public DataProduct() {
        }

        public String getUuid() {
            return uuid;
        }

        public void setUuid(String uuid) {
            this.uuid = uuid;
        }

        public String getFqn() {
            return fqn;
        }

        public void setFqn(String fqn) {
            this.fqn = fqn;
        }
    }
}

