package org.opendatamesh.platform.pp.registry.rest.v2.resources.dataproductversion.events.received;

import io.swagger.v3.oas.annotations.media.Schema;
import org.opendatamesh.platform.pp.registry.rest.v2.resources.dataproductversion.DataProductVersionRes;

@Schema(name = "ReceivedEventDataProductVersionRejectedRes", description = "Strongly-typed representation of a received DATA_PRODUCT_VERSION_PUBLICATION_REJECTED event")
public class ReceivedEventDataProductVersionRejectedRes {
    @Schema(description = "Unique identifier of the event (autogenerated sequence ID)", example = "42")
    private Long sequenceId;

    @Schema(description = "Type of the resource that generated the event", example = "DATA_PRODUCT_VERSION")
    private String resourceType;

    @Schema(description = "Identifier of the resource that generated the event", example = "d5b5b9ac-6a73-4c73-b9ce-4bfc10a1dba0")
    private String resourceIdentifier;

    @Schema(description = "Type of event emitted", example = "DATA_PRODUCT_VERSION_PUBLICATION_REJECTED")
    private String type;

    @Schema(description = "Version of the event type definition", example = "1.0.0")
    private String eventTypeVersion;

    @Schema(description = "Strongly-typed content of the event")
    private EventContent eventContent;

    public ReceivedEventDataProductVersionRejectedRes() {
    }

    public Long getSequenceId() {
        return sequenceId;
    }

    public void setSequenceId(Long sequenceId) {
        this.sequenceId = sequenceId;
    }

    public String getResourceType() {
        return resourceType;
    }

    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    public String getResourceIdentifier() {
        return resourceIdentifier;
    }

    public void setResourceIdentifier(String resourceIdentifier) {
        this.resourceIdentifier = resourceIdentifier;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getEventTypeVersion() {
        return eventTypeVersion;
    }

    public void setEventTypeVersion(String eventTypeVersion) {
        this.eventTypeVersion = eventTypeVersion;
    }

    public EventContent getEventContent() {
        return eventContent;
    }

    public void setEventContent(EventContent eventContent) {
        this.eventContent = eventContent;
    }

    @Schema(name = "EventContent", description = "Strongly-typed event content for DATA_PRODUCT_VERSION_PUBLICATION_REJECTED")
    public static class EventContent {
        @Schema(description = "The data product version that was rejected")
        private DataProductVersionRes dataProductVersion;

        public EventContent() {
        }

        public DataProductVersionRes getDataProductVersion() {
            return dataProductVersion;
        }

        public void setDataProductVersion(DataProductVersionRes dataProductVersion) {
            this.dataProductVersion = dataProductVersion;
        }
    }
}

