package org.opendatamesh.platform.pp.registry.rest.v2.resources.event;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(name = "ProcessNotificationResponseRes", description = "Resource representation of a response to a notification processing request")
public class ProcessNotificationResponseRes {
    @Schema(description = "Unique identifier of the notification (autogenerated sequence ID)", example = "101")
    private Long sequenceId;

    @Schema(description = "Type of the event that was processed", example = "DATA_PRODUCT_CREATED")
    private String eventType;

    public ProcessNotificationResponseRes(Long sequenceId, String eventType) {
        this.sequenceId = sequenceId;
        this.eventType = eventType;
    }

    public void setSequenceId(Long sequenceId) {
        this.sequenceId = sequenceId;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public Long getSequenceId() {
        return sequenceId;
    }

    public String getEventType() {
        return eventType;
    }
}
