package org.opendatamesh.platform.pp.registry.rest.v2.resources.notification;

import com.fasterxml.jackson.databind.JsonNode;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(name = "NotificationDispatchRes", description = "Resource representation of a notification dispatch sent to an observer server")
public class NotificationDispatchRes {
    @Schema(description = "Unique identifier of the notification (autogenerated sequence ID)", example = "101")
    private Long sequenceId;

    @Schema(description = "Event details associated with this notification dispatch")
    private NotificationDispatchEventRes event;

    @Schema(description = "Target observer server information where the notification is being dispatched")
    private NotificationDispatchTargetRes target;

    public NotificationDispatchRes() {
    }

    public Long getSequenceId() {
        return sequenceId;
    }

    public void setSequenceId(Long sequenceId) {
        this.sequenceId = sequenceId;
    }

    public NotificationDispatchEventRes getEvent() {
        return event;
    }

    public void setEvent(NotificationDispatchEventRes event) {
        this.event = event;
    }

    public NotificationDispatchTargetRes getTarget() {
        return target;
    }

    public void setTarget(NotificationDispatchTargetRes target) {
        this.target = target;
    }

    @Schema(name = "NotificationDispatchEventRes", description = "Event details included in the notification dispatch")
    public static class NotificationDispatchEventRes {
        @Schema(description = "Unique identifier of the event (autogenerated sequence ID)", example = "42")
        private Long sequenceId;

        @Schema(description = "Type of the resource that generated the event", example = "DATA_PRODUCT")
        private String resourceType;

        @Schema(description = "Identifier of the resource that generated the event", example = "d5b5b9ac-6a73-4c73-b9ce-4bfc10a1dba0")
        private String resourceIdentifier;

        @Schema(description = "Type of event emitted", example = "dataProduct.created")
        private String type;

        @Schema(description = "Version of the event type definition", example = "1.0.0")
        private String version;

        @Schema(description = "Serialized JSON content of the event")
        private JsonNode content;

        public NotificationDispatchEventRes() {
        }

        public Long getSequenceId() {
            return sequenceId;
        }

        public void setSequenceId(Long sequenceId) {
            this.sequenceId = sequenceId;
        }

        public String getResourceType() {
            return resourceType;
        }

        public void setResourceType(String resourceType) {
            this.resourceType = resourceType;
        }

        public String getResourceIdentifier() {
            return resourceIdentifier;
        }

        public void setResourceIdentifier(String resourceIdentifier) {
            this.resourceIdentifier = resourceIdentifier;
        }

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public String getVersion() {
            return version;
        }

        public void setVersion(String version) {
            this.version = version;
        }

        public JsonNode getContent() {
            return content;
        }

        public void setContent(JsonNode content) {
            this.content = content;
        }
    }

    @Schema(name = "NotificationDispatchTargetRes", description = "Target observer server information for the notification dispatch")
    public static class NotificationDispatchTargetRes {
        @Schema(description = "Internal name of the observer server", example = "blindata-observer")
        private String name;

        @Schema(description = "Human-readable display name of the observer server", example = "Blindata Observer")
        private String displayName;

        @Schema(description = "Base URL of the observer server", example = "https://observer.blindata.dev")
        private String baseUrl;

        @Schema(description = "API version of the observer server", example = "v1")
        private String apiVersion;

        public NotificationDispatchTargetRes() {
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getDisplayName() {
            return displayName;
        }

        public void setDisplayName(String displayName) {
            this.displayName = displayName;
        }

        public String getBaseUrl() {
            return baseUrl;
        }

        public void setBaseUrl(String baseUrl) {
            this.baseUrl = baseUrl;
        }

        public String getApiVersion() {
            return apiVersion;
        }

        public void setApiVersion(String apiVersion) {
            this.apiVersion = apiVersion;
        }
    }
}
