package org.opendatamesh.platform.pp.registry.client.notification.resources;

import com.fasterxml.jackson.databind.JsonNode;
import io.swagger.v3.oas.annotations.media.Schema;
import org.opendatamesh.platform.pp.registry.utils.resources.VersionedRes;

import java.util.List;

@Schema(name = "NotificationRes", description = "Resource representation of a notification entity in the Notification service")
public class NotificationRes extends VersionedRes {

    @Schema(description = "Unique identifier of the notification (autogenerated sequence ID)", example = "101")
    private Long sequenceId;

    @Schema(description = "Current status of the notification", example = "DELIVERED")
    private NotificationStatusRes status;

    @Schema(description = "Event associated with this notification")
    private EventRes event;

    @Schema(description = "Subscription that triggered this notification")
    private SubscriptionRes subscription;

    @Schema(description = "Error message if notification delivery failed", example = "Connection timeout while reaching observer server")
    private String errorMessage;

    public NotificationRes() {
    }

    public Long getSequenceId() {
        return sequenceId;
    }

    public void setSequenceId(Long sequenceId) {
        this.sequenceId = sequenceId;
    }

    public NotificationStatusRes getStatus() {
        return status;
    }

    public void setStatus(NotificationStatusRes status) {
        this.status = status;
    }

    public EventRes getEvent() {
        return event;
    }

    public void setEvent(EventRes event) {
        this.event = event;
    }

    public SubscriptionRes getSubscription() {
        return subscription;
    }

    public void setSubscription(SubscriptionRes subscription) {
        this.subscription = subscription;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public enum NotificationStatusRes {
        PROCESSING,
        PROCESSED,
        FAILED_TO_DELIVER,
        FAILED_TO_PROCESS
    }

    @Schema(name = "EventRes", description = "Resource representation of an event entity")
    static class EventRes extends VersionedRes {

        @Schema(description = "Unique identifier of the event (autogenerated sequence ID)", example = "42")
        private Long sequenceId;

        @Schema(description = "Type of the resource that generated the event", example = "DATA_PRODUCT")
        private String resourceType;

        @Schema(description = "Identifier of the resource that generated the event", example = "d5b5b9ac-6a73-4c73-b9ce-4bfc10a1dba0")
        private String resourceIdentifier;

        @Schema(description = "Type of event emitted")
        private String type;

        @Schema(description = "Version of the event type definition", example = "1.0.0")
        private String eventTypeVersion;

        @Schema(description = "JSON content of the event")
        private JsonNode eventContent;

        public EventRes() {
        }

        public Long getSequenceId() {
            return sequenceId;
        }

        public void setSequenceId(Long sequenceId) {
            this.sequenceId = sequenceId;
        }

        public String getResourceType() {
            return resourceType;
        }

        public void setResourceType(String resourceType) {
            this.resourceType = resourceType;
        }

        public String getResourceIdentifier() {
            return resourceIdentifier;
        }

        public void setResourceIdentifier(String resourceIdentifier) {
            this.resourceIdentifier = resourceIdentifier;
        }

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public String getEventTypeVersion() {
            return eventTypeVersion;
        }

        public void setEventTypeVersion(String eventTypeVersion) {
            this.eventTypeVersion = eventTypeVersion;
        }

        public JsonNode getEventContent() {
            return eventContent;
        }

        public void setEventContent(JsonNode eventContent) {
            this.eventContent = eventContent;
        }
    }

    @Schema(name = "SubscriptionRes", description = "Resource representation of a subscription entity")
    static class SubscriptionRes extends VersionedRes {

        @Schema(description = "Unique identifier (UUID) of the subscription", example = "6e1b2a41-2f24-4b56-8a3f-2149f1d456b7")
        private String uuid;

        @Schema(description = "Internal observerName of the subscription")
        private String name;

        @Schema(description = "Human-readable display observerName of the subscription")
        private String displayName;

        @Schema(description = "Base URL of the observer server associated with this subscription", example = "https://observer.blindata.dev/api/v1")
        private String observerServerBaseUrl;

        @Schema(description = "API version of the observer server", example = "v1")
        private String observerApiVersion;

        @Schema(description = "List of event types this subscription is subscribed to.")
        private List<SubscriptionEventTypeRes> eventTypes;

        public SubscriptionRes() {
        }

        public String getUuid() {
            return uuid;
        }

        public void setUuid(String uuid) {
            this.uuid = uuid;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getDisplayName() {
            return displayName;
        }

        public void setDisplayName(String displayName) {
            this.displayName = displayName;
        }

        public String getObserverServerBaseUrl() {
            return observerServerBaseUrl;
        }

        public void setObserverServerBaseUrl(String observerServerBaseUrl) {
            this.observerServerBaseUrl = observerServerBaseUrl;
        }

        public String getObserverApiVersion() {
            return observerApiVersion;
        }

        public void setObserverApiVersion(String observerApiVersion) {
            this.observerApiVersion = observerApiVersion;
        }

        public List<SubscriptionEventTypeRes> getEventTypes() {
            return eventTypes;
        }

        public void setEventTypes(List<SubscriptionEventTypeRes> eventTypes) {
            this.eventTypes = eventTypes;
        }
    }

    @Schema(name = "SubscriptionEventTypeRes", description = "Resource representation of a subscription-event type mapping")
    static class SubscriptionEventTypeRes {

        @Schema(description = "Type of the event type subscribed to", example = "DATA_PRODUCT_CREATED")
        private String eventType;

        public SubscriptionEventTypeRes() {
        }

        public String getEventType() {
            return eventType;
        }

        public void setEventType(String eventType) {
            this.eventType = eventType;
        }
    }

}